name: Test on Ubuntu

on: [push, pull_request, workflow_dispatch] # run on pull requests and push events, allow manual use

jobs:
  test:
    runs-on: ${{ matrix.os }} # run on every OS specified in matrix
    strategy:
      fail-fast: false  # don't quit all jobs if a single job fails
      matrix:           # set up multiple environments to test on
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9] # test python 3.6 & onward
        architecture: [x64]

    steps: # steps to take to test package
      - name: Checkout
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      - name: Setup
        uses: actions/setup-python@v2 # https://github.com/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}  # test on all python versions specified
          architecture: ${{ matrix.architecture }}      # test on all architectures specified

      - name: Test
        run: |
          pip install --upgrade -q pytest
          pip install --upgrade -q pytest-cov
          python -m pytest -v --cov=SillyStateMachine
